# generated by zon2nix (https://github.com/jcollie/zon2nix)
{
  lib,
  linkFarm,
  fetchzip,
  fetchurl,
  fetchgit,
  runCommandLocal,
  zig_0_16,
  zstd,
  name ? "zig-packages",
}:
let
  unpackZigArtifact =
    {
      name,
      artifact,
    }:
    runCommandLocal name
      {
        nativeBuildInputs = [ zig_0_16 ];
      }
      ''
        # workaround https://codeberg.org/ziglang/zig/issues/31866
        # https://github.com/Cloudef/zig2nix/issues/54
        mkdir "$TMPDIR/src" "$TMPDIR/cache" "$TMPDIR/cache/tmp"
        touch "$TMPDIR/src/build.zig"
        hash="$(cd "$TMPDIR/src" && zig fetch --global-cache-dir "$TMPDIR/cache" ${artifact})"
        mkdir "$out"
        tar zxvf "$TMPDIR/cache/p/$hash.tar.gz" --directory "$out/" --strip-components=1
      '';

  fetchZig =
    {
      name,
      url,
      hash,
      unpack,
    }:
    let
      artifact =
        if unpack then
          fetchzip {
            inherit url hash;
            nativeBuildInputs = [ zstd ];
          }
        else
          fetchurl { inherit url hash; };
    in
    unpackZigArtifact { inherit name artifact; };

  fetchGitZig =
    {
      name,
      url,
      hash,
    }:
    let
      parts = lib.splitString "#" url;
      url_base = builtins.elemAt parts 0;
      url_without_query = builtins.elemAt (lib.splitString "?" url_base) 0;
      rev_base = builtins.elemAt parts 1;
      rev =
        if builtins.match "^[a-fA-F0-9]{40}$" rev_base != null then rev_base else "refs/heads/${rev_base}";
    in
    fetchgit {
      inherit name rev hash;
      url = url_without_query;
      deepClone = false;
      fetchSubmodules = false;
    };

  fetchZigArtifact =
    {
      name,
      url,
      hash,
      unpack,
    }:
    let
      parts = lib.splitString "://" url;
      proto = builtins.elemAt parts 0;
      path = builtins.elemAt parts 1;
      fetcher = {
        "git+http" = fetchGitZig {
          inherit name hash;
          url = "http://${path}";
        };
        "git+https" = fetchGitZig {
          inherit name hash;
          url = "https://${path}";
        };
        http = fetchZig {
          inherit name hash unpack;
          url = "http://${path}";
        };
        https = fetchZig {
          inherit name hash unpack;
          url = "https://${path}";
        };
      };
    in
    fetcher.${proto};
  # The packages, as real directories holding symlinked files, rather than as
  # a farm of symlinked directories.
  #
  # Zig runs a dependency's own build steps with the working directory set to
  # that dependency, and points at the program to run with a path counted in
  # directories up from there. Through a symlink the two disagree: Zig counts
  # from `<farm>/<package>/`, four directories below the root, while the kernel
  # resolves the working directory to `/nix/store/<hash>`, which is three, so
  # the path lands one short of where the program is.
  #
  # It works anyway when the build directory is `/build`, because the sum then
  # overshoots into the root and going above the root stays there. It fails
  # when the build directory is under `/nix/var/nix/builds`, which is where Nix
  # puts it when the sandbox is off. Real directories make the two depths
  # agree, so it works either way.
  #
  # The files have to be real as well, which is the expensive part and cannot
  # be avoided. `--symbolic-link` would leave them pointing into each
  # dependency's own store path, so that the farm is a few megabytes rather
  # than a second copy of every dependency -- but Zig's
  # `installHeadersDirectory` walks the directory and copies only the entries
  # whose kind is `.file`. Symlinked headers are skipped without a word, and
  # the first thing to include one fails with `'dcimgui.h' not found`.
  #
  # `--link` is not the way out. A hard link into a Nix output is a file the
  # builder did not create: inside the Linux sandbox the store is a separate
  # mount and `link` fails with `Invalid cross-device link`, while on Darwin it
  # succeeds and leaves root-owned files in the output, which Nix refuses while
  # canonicalising with `invalid ownership on file`.
  #
  # So it is a real copy, with `--reflink=auto` to share the blocks on a
  # filesystem that can. `nix store optimise` recovers the duplication after
  # the fact, hard-linking identical files across the store, which is the
  # store's own business to do and not a build's.
  copyFarm =
    farm: entries: pathDependencyPackages:
    runCommandLocal farm
      {
        # The packages whose own manifest declares a dependency by `.path`.
        # Zig 0.16.0 cannot build these through `zig build --system`: it spins
        # in userspace forever, because a `.path` dependency's hash is computed
        # against the system package directory during the fetch and against the
        # real global cache afterwards, and in that mode the two disagree. A
        # package that wants `--system` copies each of these into its build
        # root and passes `--fork=`; see the README.
        passthru = { inherit pathDependencyPackages; };
      }
      ''
        mkdir -p "$out"
        cp --recursive --reflink=auto --dereference --no-preserve=mode \
          ${linkFarm farm entries}/. "$out/"
      '';
in
copyFarm name
  [
    {
      name = "benchmark-0.1.0-JS72VvXxAACo8j9BYddbkivgNHXIeD1V27013BuCtW-_";
      path = fetchZigArtifact {
        name = "benchmark";
        url = "git+https://github.com/mattrobenolt/zig-benchmark#6e7e9ab7ed8bd8147c491ac53a1d326633a5c47a";
        hash = "sha256-T8xU4EMmCI2nM3xtfdpjnZJGrZs7RwNcqwspAsUEgLc=";
        unpack = true;
      };
    }
    {
      name = "benchmark-0.1.0-JS72VkomAQAHiEPwJB4rOn0vjLChZnQhcMqVKLPFZCQ4";
      path = fetchZigArtifact {
        name = "benchmark";
        url = "git+https://github.com/mattrobenolt/zig-benchmark#bc978caebd4424c99a84e9329a9ea847cc7a22e4";
        hash = "sha256-JTsa/KryXNpU722+uq95aQwi0+sYQK27hTIWyXaX3AY=";
        unpack = true;
      };
    }
    {
      name = "libxev-0.0.0-86vtc6BWFAAs_tGsasNfjQsxSsElhddIUnqVwGhwdnsu";
      path = fetchZigArtifact {
        name = "libxev";
        url = "git+https://github.com/mitchellh/libxev#7497c85dfc3ae5141308944f2cd47c836772c300";
        hash = "sha256-UnJ/L/IA2pgWQ5MY+w+RDlyg56asNKHTp86SARWoESU=";
        unpack = true;
      };
    }
    {
      name = "txtar-0.1.0-RyJLBJ5rAABCV5lD0YSt048wd3l9Nk9a4_TnEnm0MZ9P";
      path = fetchZigArtifact {
        name = "txtar";
        url = "git+https://github.com/mattrobenolt/txtar#85c27385a0c14a1129a653af363a334266d48734";
        hash = "sha256-f9IUp0otf2MLdhsk1bgK99E4GIzmG8Y58tJpIrMybHM=";
        unpack = true;
      };
    }
    {
      name = "ztest-0.2.0-h6PBzx2NAACI2wKYtRDq8PUTvjyyRYuPB_Xcw4UK4Vk9";
      path = fetchZigArtifact {
        name = "ztest";
        url = "git+https://github.com/mattrobenolt/ztest#ab7a2ed05547340261dd8f12a564aefc2950df91";
        hash = "sha256-FwcGqCtf9uiXyWQOKse8CSLVTL29BIoiXuWJOILN7RA=";
        unpack = true;
      };
    }
    {
      name = "ztest-0.2.0-h6PBzyKEAAC49mtm1NO2CTeniItVuL0l06TpBDMDTe19";
      path = fetchZigArtifact {
        name = "ztest";
        url = "https://github.com/mattrobenolt/ztest/archive/e8a7c83a961502ff85ed82fbab06af78c81a0836.tar.gz";
        hash = "sha256-+p5tcPFxYeLw+XB3L9GjZ05/9QLVbwMJROTPt6VpxGM=";
        unpack = true;
      };
    }
    {
      name = "ztls-0.0.0-SHHDXqSOIwD4s3C21oPI3P9KCfMZRF2OCVUhbTgNLvps";
      path = fetchZigArtifact {
        name = "ztls";
        url = "git+https://github.com/mattrobenolt/ztls?ref=main#3894246d1d99e51b0e99d0e4f02146a983f16927";
        hash = "sha256-bErF4B2/D8hOC8bNlixJkNzAWd3qFZkyNAIu1V9Triw=";
        unpack = true;
      };
    }
  ]
  [
  ]
